<template>
  <ui-h
    id="buttons"
    level="2"
    class="mb2"
  >
    Buttons
  </ui-h>
  <ui-card>
    <ui-h
      id="buttons-default"
      level="3"
      class="mb2"
    >
      Default
    </ui-h>
    <div class="flex-row-wrap">
      <ui-button>
        Submit
      </ui-button>
      <ui-button
        disabled
      >
        Disabled
      </ui-button>
    </div>
  </ui-card>
  <ui-card>
    <ui-h
      id="buttons-severities"
      level="3"
      class="mb2"
    >
      Severities
    </ui-h>
    <div class="flex-row-wrap">
      <ui-button seriousness="primary">
        Primary
      </ui-button>
      <ui-button seriousness="secondary">
        Secondary
      </ui-button>
      <ui-button seriousness="success">
        Success
      </ui-button>
      <ui-button seriousness="info">
        Info
      </ui-button>
      <ui-button seriousness="warning">
        Warning
      </ui-button>
      <ui-button seriousness="danger">
        Danger
      </ui-button>
    </div>
  </ui-card>
  <ui-card>
    <ui-h
      id="buttons-text"
      level="3"
      class="mb2"
    >
      Text
    </ui-h>
    <div class="flex-row-wrap">
      <ui-button
        appearance="text"
        seriousness="primary"
      >
        Primary
      </ui-button>
      <ui-button
        appearance="text"
        seriousness="secondary"
      >
        Secondary
      </ui-button>
      <ui-button
        appearance="text"
        seriousness="success"
      >
        Success
      </ui-button>
      <ui-button
        appearance="text"
        seriousness="info"
      >
        Info
      </ui-button>
      <ui-button
        appearance="text"
        seriousness="warning"
      >
        Warning
      </ui-button>
      <ui-button
        appearance="text"
        seriousness="danger"
      >
        Danger
      </ui-button>
    </div>
  </ui-card>
  <ui-card>
    <ui-h
      id="buttons-outlined"
      level="3"
      class="mb2"
    >
      Outlined
    </ui-h>
    <div class="flex-row-wrap">
      <ui-button
        appearance="outlined"
        seriousness="primary"
      >
        Primary
      </ui-button>
      <ui-button
        appearance="outlined"
        seriousness="secondary"
      >
        Secondary
      </ui-button>
      <ui-button
        appearance="outlined"
        seriousness="success"
      >
        Success
      </ui-button>
      <ui-button
        appearance="outlined"
        seriousness="info"
      >
        Info
      </ui-button>
      <ui-button
        appearance="outlined"
        seriousness="warning"
      >
        Warning
      </ui-button>
      <ui-button
        appearance="outlined"
        seriousness="danger"
      >
        Danger
      </ui-button>
    </div>
  </ui-card>
  <ui-card>
    <ui-h
      id="buttons-rounded"
      level="3"
      class="mb2"
    >
      Rounded
    </ui-h>
    <div class="flex-row-wrap">
      <ui-button
        appearance="rounded"
        seriousness="primary"
      >
        Primary
      </ui-button>
      <ui-button
        appearance="rounded"
        seriousness="secondary"
      >
        Secondary
      </ui-button>
      <ui-button
        appearance="rounded"
        seriousness="success"
      >
        Success
      </ui-button>
      <ui-button
        appearance="rounded"
        seriousness="info"
      >
        Info
      </ui-button>
      <ui-button
        appearance="rounded"
        seriousness="warning"
      >
        Warning
      </ui-button>
      <ui-button
        appearance="rounded"
        seriousness="danger"
      >
        Danger
      </ui-button>
    </div>
  </ui-card>
  <ui-card>
    <ui-h
      id="buttons-rounded-text"
      level="3"
      class="mb2"
    >
      Rounded Text
    </ui-h>
    <div class="flex-row-wrap">
      <ui-button
        appearance="rounded-text"
        seriousness="primary"
      >
        Primary
      </ui-button>
      <ui-button
        appearance="rounded-text"
        seriousness="secondary"
      >
        Secondary
      </ui-button>
      <ui-button
        appearance="rounded-text"
        seriousness="success"
      >
        Success
      </ui-button>
      <ui-button
        appearance="rounded-text"
        seriousness="info"
      >
        Info
      </ui-button>
      <ui-button
        appearance="rounded-text"
        seriousness="warning"
      >
        Warning
      </ui-button>
      <ui-button
        appearance="rounded-text"
        seriousness="danger"
      >
        Danger
      </ui-button>
    </div>
  </ui-card>
  <ui-card>
    <ui-h
      id="buttons-rounded-outlined"
      level="3"
      class="mb2"
    >
      Rounded Outlined
    </ui-h>
    <div class="flex-row-wrap">
      <ui-button
        appearance="rounded-outlined"
        seriousness="primary"
      >
        Primary
      </ui-button>
      <ui-button
        appearance="rounded-outlined"
        seriousness="secondary"
      >
        Secondary
      </ui-button>
      <ui-button
        appearance="rounded-outlined"
        seriousness="success"
      >
        Success
      </ui-button>
      <ui-button
        appearance="rounded-outlined"
        seriousness="info"
      >
        Info
      </ui-button>
      <ui-button
        appearance="rounded-outlined"
        seriousness="warning"
      >
        Warning
      </ui-button>
      <ui-button
        appearance="rounded-outlined"
        seriousness="danger"
      >
        Danger
      </ui-button>
    </div>
  </ui-card>
</template>

<script
  setup
  lang="ts"
>
import UiButton from '@/components/ui/UiButton.vue'
import UiCard from '@/components/ui/UiCard.vue'
import UiH from '@/components/ui/UiH.vue'
</script>

<style
  lang="scss"
  scoped
>

</style>